# Prerelease workflow - we are much more lax in this workflow. No linting
# and no changelog.

# SPDX-FileCopyrightText: 2022 Johannes Loher
#
# SPDX-License-Identifier: MIT

name: Release

on:
  release:
    types: [prereleased]

env:
  package_type: module
  node_version: latest

jobs:
  build:
    if: ${{github.event.release.prerelease}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: npm

      - name: Extract tag version number
        id: get_version
        run: echo "version-without-v=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: devops-actions/variable-substitution@v1.2
        with:
          files: "static/${{ env.package_type }}.json"
        env:
          version: ${{ steps.get_version.outputs.version-without-v }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/${{ env.package_type }}.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/${{ env.package_type }}.zip

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    if: ${{github.event.release.prerelease == true}}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download production artifacts for publication
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Extract tag version number
        id: get_version
        run: echo "version-without-v=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Create zip file
        working-directory: ./dist
        run: zip -r ../${{ env.package_type }}.zip .

      - name: Create pre-release
        if: ${{ github.event.release.prerelease }}
        id: create_version_prerelease
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          makeLatest: false
          prerelease: true
          name: ${{ github.event.release.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/${{ env.package_type }}.json, ./${{ env.package_type }}.zip"
